[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_CHAIN_ID = "97"
  VITE_RPC_URL = "https://data-seed-prebsc-1-s1.binance.org:8545/"
  VITE_VAULT_ADDRESS = "0x4625bB7f14D4e34F9D11a5Df7566cd7Ec1994849"
  VITE_STRATEGY_AAVE_ADDRESS = "0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8b6"
  VITE_STRATEGY_PANCAKE_ADDRESS = "0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8b6"
  VITE_STRATEGY_UNISWAP_ADDRESS = "0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8b6"
  VITE_STRATEGY_MORPHO_ADDRESS = "0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8b6"
  VITE_ENVIRONMENT = "production"
  VITE_DEBUG_MODE = "false"
  VITE_ENABLE_TESTNETS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200